name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
    paths-ignore:
      - '*.md'

  pull_request:
    branches: [main, develop]
    paths-ignore:
      - '*.md'

jobs:
  get-matrix:
    uses: ./.github/workflows/_matrix-config.yml

  build-windows:
    name: windows-${{ matrix.c_compiler }}-qt${{ matrix.qt_version }}
    needs: get-matrix
    strategy:
      fail-fast: false
      matrix:
        qt_version: ${{ fromJson(needs.get-matrix.outputs.qt_versions) }}
        c_compiler: ${{ fromJson(needs.get-matrix.outputs.compilers_windows) }}
        include:
          - c_compiler: cl
            cpp_compiler: cl
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++

    uses: ./.github/workflows/_build-shared.yml
    with:
      os: windows-latest
      c_compiler: ${{ matrix.c_compiler }}
      cpp_compiler: ${{ matrix.cpp_compiler }}
      qt_version: ${{ matrix.qt_version }}
